### ISSUE TITLE
This project is not licensed under GPLv2

### ISSUE THREAD

**Issue by QuinnWilton** [dmg9626/This-Is-Trump#2]
As it stands now, I don't feel comfortable supporting the project.

**Comment by borski** [comment]
MIT license would be fine as well, or Apache. This is a blocker for me as well - I really want to use this, but my boss won't let me unless we have the licensing worked out.

**Comment by QuinnWilton** [comment]
That's fair. I understand that GPLv2 can be scary for some people. Might I suggest dual licensing the project as GPLv2/MIT?

**Comment by dmg9626** [comment]
what is this some kind of meme

**Comment by QuinnWilton** [comment]
The law is no meme, Drew.

**Comment by borski** [comment]
For what it's worth, this is easier to do now than later - later, you'll have to ask each individual contributor if they're OK with the license change.

**Comment by borski** [comment]
Bump? I really need this and it's blocking me in production.

**Comment by dmg9626** [comment]
Added GPLv2 license
